#ifndef ML_ADC0_H
#define ML_ADC0_H

#include <Arduino.h>

#ifdef __cplusplus
extern "C"
{
#endif 

#define ML_ADC0_DEFAULT_CHANNEL_SETTINGS (DMAC_CHCTRLA_BURSTLEN_SINGLE | DMAC_CHCTRLA_TRIGACT_BURST | DMAC_CHCTRLA_TRIGSRC(ADC0_DMAC_ID_RESRDY))
#define ML_ADC0_DEFAULT_DESCRIPTOR_SETTINGS (DMAC_BTCTRL_DSTINC | DMAC_BTCTRL_BEATSIZE_HWORD | DMAC_BTCTRL_BLOCKACT_BOTH | DMAC_BTCTRL_EVOSEL_BURST | DMAC_BTCTRL_VALID)



void ADC0_init(void);

#ifdef __cplusplus
}
#endif 


#endif